### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by floogulinc** [theirc/web.refugee.info#325]
For a website targeted at mobile use and for critical information, it should really be optimized for speed and small size. The site is over 1mb on first load and takes about 1 min to load on 2G and even on a gigabit fiber connection with a fast computer it can take over 5 seconds to load. This could be decreased substantially as it's not a very complex site. In the situations this site is intended for, fast loading and low data usage is very important. Offline support with service workers would also likely help a lot. The javascript heavy nature of the site may also lead to performance issues on lower spec devices and is entirely unusable without javascript enabled.

Google PageSpeed Insights [rates the page poor](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.refugee.info%2Fserbia%2F) with 51/100 on mobile.

**Comment by kkaczmarczyk** [comment]
Thanks for raising your concerns - these will be considered.
